# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

movement_init <- function(parameters) {
    .Call('_macro_movement_init', PACKAGE = 'macro', parameters)
}

movement_step <- function(module, time_step) {
    .Call('_macro_movement_step', PACKAGE = 'macro', module, time_step)
}

convert_to_r_movement <- function(movement_list, human) {
    invisible(.Call('_macro_convert_to_r_movement', PACKAGE = 'macro', movement_list, human))
}

movements_of_human <- function(movement_list, human) {
    .Call('_macro_movements_of_human', PACKAGE = 'macro', movement_list, human)
}

