# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize Flux Movement module
#'
#' This function returns a flux movement module.
#'
#' @param parameters A list containing random_seed, random_stream,
#'        human_count, patch_count, and a flow_probability vector.
#' @param initial_location A vector saying in which patch each human is located.
#'
#' @examples
#' \dontrun{
#' movement <- movement_init(params)
#' time_step <- 0.1
#' moves <- movement_step(movement, time_step)
#' person <- human_model(moves, time_step)
#' }
flux_movement_init <- function(parameters, initial_location) {
    .Call('_macro_flux_movement_init', PACKAGE = 'macro', parameters, initial_location)
}

#' Time step for a flux movement module.
#'
#' @param module The flux movement list
#' @param time_step A floating point time.
#' @return A result list that is opaque.
flux_movement_step <- function(module, time_step) {
    .Call('_macro_flux_movement_step', PACKAGE = 'macro', module, time_step)
}

#' Convert movement result to R data
#'
#' The result of a movement object is in C++. This extracts
#' it into an R list. The result is added to the original
#' list that was passed in.
#'
#' @param movement The movement module object
#' @param human An integer vector of which human positions to extract.
#' @returns Movement list with a "moves" list that has human locations.
convert_to_r_movement <- function(movement, human) {
    .Call('_macro_convert_to_r_movement', PACKAGE = 'macro', movement, human)
}

movements_of_human <- function(movement_list, human) {
    .Call('_macro_movements_of_human', PACKAGE = 'macro', movement_list, human)
}

#' Generate Mersenne Twister seed states skipped ahead by powers of two.
#'
#' A Mersenne Twister random number generator can be skipped ahead
#' by large numbers of random numbers. This function uses the Boost
#' implementation of that algorithm to skip ahead its version of
#' mt19937, not mt19937_64.
#'
#' @param seed A single number, without too many 0 bits, to
#'        initialize the random number generator.
#' @param skip_size_power_two The jump will be two raised to this
#'        power. If it is 14 or greater, it will use the
#'        special algorithm.
#' @param skip_count How many times to skip forward. This is
#'        the number of simultaneous streams you want to use.
#' @return A matrix of size 624 by skip_count. Put the 624
#'         into the Mersenne seed in order to initialize it.
#'
#' @export
skip_mersenne_twister <- function(seed, skip_size_power_two, skip_count) {
    .Call('_macro_skip_mersenne_twister', PACKAGE = 'macro', seed, skip_size_power_two, skip_count)
}

